name: user_repository
description: The Reop that handles users
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.1.0
  intl: ^0.19.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  flutter_bloc: ^8.1.4
  firebase_core: ^2.25.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
