// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ZucQTIVOKse7lnmL7zz-TI0oQ-Vmrb4',
    appId: '1:977400170801:web:aa956921dbcc15ddac4810',
    messagingSenderId: '977400170801',
    projectId: 'habit-tracker-5f973',
    authDomain: 'habit-tracker-5f973.firebaseapp.com',
    storageBucket: 'habit-tracker-5f973.appspot.com',
    measurementId: 'G-V06RW3W10X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAgJtehYMFEWAoCjrb6nq7D7IlY9jxo_E',
    appId: '1:977400170801:android:88f8c49bf47fda37ac4810',
    messagingSenderId: '977400170801',
    projectId: 'habit-tracker-5f973',
    storageBucket: 'habit-tracker-5f973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZXkz6T2HLXVypZsXf2C85q3buEVGEMag',
    appId: '1:977400170801:ios:b9af319c88b99d91ac4810',
    messagingSenderId: '977400170801',
    projectId: 'habit-tracker-5f973',
    storageBucket: 'habit-tracker-5f973.appspot.com',
    iosClientId: '977400170801-7lf7kmra509htdk5bqkgqt3hprs0sca1.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZXkz6T2HLXVypZsXf2C85q3buEVGEMag',
    appId: '1:977400170801:ios:238e81b4237cb645ac4810',
    messagingSenderId: '977400170801',
    projectId: 'habit-tracker-5f973',
    storageBucket: 'habit-tracker-5f973.appspot.com',
    iosClientId: '977400170801-pd571pcgp3lg5mu4ohunlk5hf7rp7f5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker.RunnerTests',
  );
}
